# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-20 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hw',
            name='hw_content',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='hw',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hw', to='assignments.Task'),
        ),
    ]
