# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-20 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20180420_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
