# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-20 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_hw_hw_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hw',
            name='hw_object',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
